# Generated by Django 4.2.16 on 2026-09-24 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_purchases', models.PositiveIntegerField()),
                ('purchase_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Rarely', 'Rarely')], max_length=20)),
                ('preferred_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Groceries', 'Groceries'), ('Sports', 'Sports'), ('Home & Garden', 'Home & Garden'), ('Books', 'Books'), ('Beauty', 'Beauty'), ('Toys', 'Toys')], max_length=50)),
                ('is_demo', models.BooleanField(default=False, help_text='True if this is synthetic demo data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('testing_samples', models.IntegerField(blank=True, null=True)),
                ('features', models.JSONField(default=list)),
                ('target', models.CharField(default='recommended_category', max_length=100)),
                ('dataset_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Model Info',
                'verbose_name_plural': 'Model Infos',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_category', models.CharField(max_length=100)),
                ('recommended_product', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('model_algorithm', models.CharField(blank=True, max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendation.customer')),
            ],
            options={
                'verbose_name_plural': 'Recommendation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
