# Generated by Django 4.2.16 on 2026-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelInfo',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='is_demo',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='model_algorithm',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='recommended_category',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='recommended_product',
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='cluster_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='customer_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='frequency',
            field=models.IntegerField(default=0, help_text='Total invoice count'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='monetary',
            field=models.FloatField(default=0.0, help_text='Total spend (£)'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recency',
            field=models.IntegerField(default=0, help_text='Days since last purchase'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommended_products',
            field=models.JSONField(default=list, help_text='List of recommended products'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='segment',
            field=models.CharField(default='General', help_text='K-Means Cluster Segment', max_length=100),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
