# Generated by Django 4.2.16 on 2026-09-28 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_businessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='recommendation.businessprofile')),
            ],
            options={
                'verbose_name': 'Business Customer',
                'verbose_name_plural': 'Business Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Customer ID string or number', max_length=100),
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0.0)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='recommendation.businesscustomer')),
            ],
            options={
                'verbose_name': 'Purchase Transaction',
                'verbose_name_plural': 'Purchase Transactions',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
